name: release

on:
  push:
    tags:
      - v*

jobs:
  
  # This CI job runs the type checker (pytype) and unit tests (pytest) with tox
  tox:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Update pip, setuptools, and wheel
        run: pip install --upgrade pip setuptools wheel
      - name: Install tox
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
  
  # This CD job deploys the package to PyPI. It only runs if the CI job is successful and if we tag a commit with a new version number
  # This is a separate job entirely because it only needs to run once (and avoids the matrix of python versions in the previous job)
  pypi:
    needs: [tox]
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update pip, setuptools, and wheel
        run: pip install --upgrade pip setuptools wheel
      - name: Install build and twine
        run: pip install build twine
      - name: Build distribution and deploy to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m build
          twine upload dist/*
  
  # This CD job builds a Docker image and pushes it to Docker Hub. It only runs if the CI job is successful and if we tag a commit with a new version number
  docker:
    needs: [tox]

    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_IMAGE: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v2
      - name: Set GIT_TAG environment variable
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to the container registry
        run: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - name: Build the Docker image
        run: docker build -t $DOCKER_IMAGE:$GIT_TAG -t $DOCKER_IMAGE:latest .
      - name: Push the Docker image to the container registry
        run: docker push --all-tags $DOCKER_IMAGE
      
